name: NCBack
favicon: null
layout_spectrum: 0.4978
typography_spectrum: 0.48935599508695304
title: 'Asheville Chiropractic '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#313131'
    - '#929292'
    - '#b7b7b7'
  brandStrength: 0.5
  lightness: 0.41961185238324106
  saturation: 0.46592130954377353
  rhythmicContrast: 0.25
purpose: []
