name: NCBack
favicon: null
layout_spectrum: 0.99295
typography_spectrum: 0.48935599508695304
title: 'Asheville Chiropractic '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e6e9ee'
    - '#130e0b'
    - '#77431e'
    - '#9fa6ae'
    - '#7d7642'
  brandStrength: 0.75
  lightness: 0.875
  saturation: 0.0625
  rhythmicContrast: 0.5
purpose: []
